### ISSUE TITLE
Segfault on Python 3.12

### ISSUE THREAD

**Issue by NickGeek** [rchaput/xdg-prefs#11]
Hi, I just attempted to install and run this with Python 3.12 on x86_64 Arch Linux. I get a segmentation fault when attempting to launch the program. I put the core dump in the debugger and it appears that there is a bad pointer deference in `PyDict_GetItem` within cpython. I think it's a case of bad FFI.

Specifically:
```
PyDict_GetItem:
	endbr64                         
	push   %rbp                     
	mov    %rsp,%rbp                
	push   %r15                     
	push   %r14                     
	push   %r13                     
	push   %r12                     
	push   %rbx                     
	sub    $0x18,%rsp               
	mov    %fs:0x28,%rax            
	mov    %rax,-0x38(%rbp)         
	mov    0x8(%rdi),%rax    ; %rdi is null, 0x8(0x0) is invalid memory
```

**Comment by rchaput** [comment]
Hi, I have not been working on this project for a long time, so it does not surprise me that there is a problem with recent versions of Python. You can try using an old version (e.g., 3.7, even though it's now deprecated).

It seems that there is a problem with indexing a dictionary, however the error you reported does not show where. It's strange that an indexation would cause a segfault, usually Python handles this and raises an exception.
Could you try adding the line `logging.basicConfig(level='DEBUG')` in the `main()` method in the `xdgprefs/__main__.py` file, between lines 12 and 13 and tell me what the logs show?
(I should have added support for setting the log level through an environment variable)

**Comment by NickGeek** [comment]
We never make it that far, `from PySide2.QtWidgets import QApplication` causes the segfault.

My understanding is that a few people are getting crashes with different libs on Python 3.12 due to some changes in FFI handling. I suspect updating the Qt dependency might fix it.

**Comment by NickGeek** [comment]
Looking to https://wiki.qt.io/Qt_for_Python#Python_compatibility_matrix, it looks like there is a pretty limited window of compatibility.

**Comment by rchaput** [comment]
> We never make it that far, `from PySide2.QtWidgets import QApplication` causes the segfault.

Okay, this makes more sense: an error in Python should raise a Python exception, but since PySide2 is just a binding to C/C++ code (Qt), the segfault seems logical.

> My understanding is that a few people are getting crashes with different libs on Python 3.12 due to some changes in FFI handling. I suspect updating the Qt dependency might fix it.

I thought that, by not specifying a version for PySide2 in the `requirements.txt`, this project would be "future-proof" and always using up-to-date dependencies. However, it seems that the Qt organization has created another library, `PySide6` for Qt6.
This means that we have to:
1. Replace all occurrences of `PySide2` to `PySide6`;
2. Ensure that the code works with this newer version. The official documentation describes how to port existing apps: https://doc.qt.io/qtforpython-6/gettingstarted/porting_from2.html

Note that, if Qt5 is used, PySide2 must be imported rather than PySide6...

I will try to make a quick commit tomorrow with a fix for PySide6, and I will deal later with the "defaulting back to PySide2" problem.

**Comment by NickGeek** [comment]
I have got it working locally with PySide6. I'll push up shortly as a fork if you'd like to merge it in the future.

The downside is that it drops support for Python <3.9 and also requires Qt 6.

**Comment by rchaput** [comment]
Thanks for the PR, it helps a lot. I've merged it and released a new version with your fix.

In the end, I added instructions to download the previous v0.2 for users who need Python 3.6 or Qt5. This is easier than trying to default back to PySide2 (I'm not sure whether we can determine the Qt version without crashing the app?).
