### ISSUE TITLE
PackageNotFoundError: No package metadata was found for XDG-Prefs

### ISSUE THREAD

**Issue by Jogai** [rchaput/xdg-prefs#9]
Trying to run this on EndeavourOS Linux x86_64 (with openbox/lxqt) results in an error. I did compile it, but I never did a lot of python development so I'm a bit lost.

running `./compiled/bin/xdg-prefs` gives me:
```
Traceback (most recent call last):                                                                                                              
  File "/home/jogai/Projects/xdg-prefs/./compiled/bin/xdg-prefs", line 33, in <module>
    sys.exit(load_entry_point('XDG-Prefs==0.1', 'gui_scripts', 'xdg-prefs')())
  File "/home/jogai/Projects/xdg-prefs/./compiled/bin/xdg-prefs", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for XDG-Prefs
```

Build command:
`python setup.py install --prefix compiled/`

output of `tree compiled/ -L 4`:
```
tree compiled/ -L 4                                                                                          
compiled/                                                                                                                                       
|-- bin
|   |-- future-fstrings-show
|   |-- pyside2-designer
|   |-- pyside2-lupdate
|   |-- pyside2-rcc
|   |-- pyside2-uic
|   `-- xdg-prefs
`-- lib
    `-- python3.10
        `-- site-packages
            |-- PySide2-5.15.2.1-py3.10-linux-x86_64.egg
            |-- XDG_Prefs-0.1-py3.10.egg
            |-- future_fstrings-1.2.0-py3.10.egg
            `-- shiboken2-5.15.2.1-py3.10-linux-x86_64.egg
```

**Comment by rchaput** [comment]
If I understand correctly, Python does not find the package, although it seems to be present in your `compiled/lib/python3.10/site-packages/XDG_Prefs-0.1-py3.10egg`.
This intuition seems correct, since the error does not appear when I change the `PYTHONPATH` environment variable (which controls the directories in which Python looks for packages).

The following command works for me:
```sh
PYTHONPATH="./compiled/lib/python3.10/site-packages/" ./compiled/bin/xdg-prefs
```

However, it is not very practical... A long-term solution seems to be using `pip install -e .` after `python setup.py install --prefix=compiled/`. The `pip install` command will install the "xdg-prefs" package into your global (system-wide) packages site, which is then detected by Python when using `./compiled/bin/xdg-prefs`.

**Comment by Jogai** [comment]
Installing python-shiboken2 & pyside2 trough pacman solved my problem.
